### ISSUE TITLE
Site et mise à jour des documents de mise en conformité

### ISSUE THREAD

**Issue by OMoukoko** [SocialGouv/medle#109]
Hello l'équipe,

Nous passons en revue les sites des produits de la Fabrique dans le cadre de la mise en conformité et nous avons plusieurs remarques sur les documents de conformité mis en ligne :
- les liens vers la politique de confidentialité (au premier niveau et au second niveau du bandeau cookie ) ne fonctionnent pas. La dernière version à jour de la politique de confidentialité de Medlé se trouve directement dans le nextcloud de la Fabrique, dans la partie RGPD (dossier Medlé). 

<img width="1440" alt="Capture d’écran 2021-02-23 à 14 58 39" src="https://user-images.githubusercontent.com/79263610/108854039-b20ca380-75e7-11eb-939f-7d39d56df1e2.png">

- Les mentions légales ne sont pas visibles sur le site ; Ces dernières se trouvent également dans le nextcloud de la Fabrique ;
- Serait-il possible d'avoir un accès en ligne et direct à la plateforme ? 

A votre disposition pour répondre à toute question ;

Très cordialement,
Osiris Moukoko Priso

**Comment by pom421** [comment]
Bonjour @OMoukoko, 

"Serait-il possible d'avoir un accès en ligne et direct à la plateforme ?". 
=> Tu proposes de rajouter un lien qui permette de voir les mentions légales dès la première page, c'est ça ?

Pour la politique de confidentialité, il n'y a à l'heure actuelle que Hotjar et Matomo/Piwik. On nous a demandé de supprimer Hotjar, donc on va pouvoir se passer du panneau pour les cookies. Dans ce cas, j'imagine qu'il n'y a plus lieu d'avoir de politique de confidentialité.

cc @saniyaas

**Comment by OMoukoko** [comment]
Bonjour @pom421 

Pour l'accès en ligne, non nous souhaiterions avoir nous un accès à la plateforme (comme utilisateurs test) pour pouvoir voir les documents et là où il faut les installer. Le droit à l'information, passant par un accès facile aux dites informations, il sera plus aisé de vous indiquer où mettre les documents. 

Pour la politique de confidentialité, celle-ci est un document obligatoire dès qu'on traite des données, indépendamment des cookies. Il ne faudra donc pas le supprimer. En revanche, effectivement, dès lors que vous aurez supprimé Hotjar, le bandeau cookies ne sera plus nécessaire, la politique de confidentialité permettant aux utilisateurs d'être informés sur l'existence de Matomo.

Très cordialement

**Comment by pom421** [comment]
Bonjour, 

Un compte test@numericite.fr (avec le mot de passe testtest) a été créé sur la plateforme de recette https://medle-dev.fabrique.social.gouv.fr. Avec ce compte, vous pouvez créer des actes, et créer des etp, ainsi que voir les statistiques. 

Sur NextCloud, je n'arrive pas à trouver le fichier sur la politique de confidentialité. Pouvez-vous nous l'envoyer à moi et @saniyaas, svp ?

**Comment by OMoukoko** [comment]
Bonjour,

Je vous remercie pour le compte.
Voici le lieu où se trouve la politique de confidentialité (je n'avais pas précisé qu'elle était dans le dossier RGPD - Medlé) :

https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/Fabrique/Conformit%C3%A9/RGPD/%5BMedL%C3%A9%5D&fileid=6251 

Vous trouverez l'ensemble des documents.

Voici plus spécifiquement la politique de confidentialité  : 
[[Medlé] - Politique de confidentialité V2.docx](https://github.com/SocialGouv/medle/files/6082867/Medle.-.Politique.de.confidentialite.V2.docx)

Très cordialement,

Osiris Moukoko Priso

**Comment by pom421** [comment]
Fait dans la v1.8.0 👍
